import Mathlib.RingTheory.RootsOfUnity.Basic
import Mathlib.Data.Nat.Fib.Basic
import Mathlib.Tactic

/-!
# The field identification `ℚ(ζ₅)⁺ ≅ ℚ(√5)` — algebraic core

One of the three field-theoretic wrappers of Kummer's lemma `p = 5` (see
`BealGoldenKummerEngine`, `NEXT-STEPS`): the maximal totally real subfield of `ℚ(ζ₅)` is the
real quadratic field `ℚ(√5)`, and its fundamental unit is the golden ratio `φ`.

The real subfield is generated by `η = ζ + ζ⁻¹ = 2cos(2π/5)`. This file proves the algebraic
heart of the identification, self-contained from `ζ⁵ = 1` and the geometric sum
`1 + ζ + ζ² + ζ³ + ζ⁴ = 0` (no number-field / CM machinery, fast to compile):

* **`golden_subfield_poly`** — `η² + η − 1 = 0`: the real generator `η = ζ + ζ⁴` is a root of
  `x² + x − 1`, the minimal polynomial whose splitting field is `ℚ(√5)`.
* **`golden_subfield_sqrt5`** — `(2η + 1)² = 5`: so `√5 = 2η + 1 ∈ ℚ(η)`, i.e. the real subfield
  `ℚ(η) = ℚ(ζ₅)⁺` *contains* `√5`. Together with the degree count (`[ℚ(η):ℚ] = 2`) this is the
  identification `ℚ(ζ₅)⁺ = ℚ(√5)`.
* **`golden_ratio_eq`** — `φ² − φ − 1 = 0` for `φ = 1 + η = 1 + ζ + ζ⁴ = (1 + √5)/2`: the golden
  ratio of `BealGoldenKummerEngine` realized inside `ℚ(ζ₅)`. This is the bridge from the cyclotomic
  descent to the golden-ratio arithmetic engine.

`x² + x − 1` has discriminant `5`, so `ℚ(η) = ℚ(√5)`; `φ = 1 + η` is the fundamental unit. These
identities are the precise content meant by "`ℚ(ζ₅)⁺ ≅ ℚ(√5)`, Gauss sum" in the roadmap.
-/

namespace BealFiveRealSubfieldIso

variable {K : Type*} [Field K]

/-- The geometric sum vanishes at a primitive `5`-th root: `1 + ζ + ζ² + ζ³ + ζ⁴ = 0`. -/
theorem geom_sum_five {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    1 + ζ + ζ ^ 2 + ζ ^ 3 + ζ ^ 4 = 0 := by
  have h := hζ.geom_sum_eq_zero (by norm_num)
  rw [Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_succ,
    Finset.sum_range_succ, Finset.sum_range_one] at h
  simpa [pow_succ] using h

/-- **`η² + η − 1 = 0`.** The real generator `η = ζ + ζ⁻¹ = ζ + ζ⁴` of the maximal real subfield
of `ℚ(ζ₅)` is a root of `x² + x − 1` — the minimal polynomial of `(√5 − 1)/2`. -/
theorem golden_subfield_poly {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (ζ + ζ ^ 4) ^ 2 + (ζ + ζ ^ 4) - 1 = 0 := by
  have h5 : ζ ^ 5 = 1 := hζ.pow_eq_one
  have hsum := geom_sum_five hζ
  linear_combination (ζ ^ 3 + 2) * h5 + hsum

/-- **`(2η + 1)² = 5`.** Hence `√5 = 2η + 1` lies in the real subfield `ℚ(η) = ℚ(ζ₅)⁺`: the
identification `ℚ(ζ₅)⁺ ⊇ ℚ(√5)` (an equality by the degree count `[ℚ(η):ℚ] = 2`). -/
theorem golden_subfield_sqrt5 {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (2 * (ζ + ζ ^ 4) + 1) ^ 2 = 5 := by
  have hp := golden_subfield_poly hζ
  linear_combination 4 * hp

/-- **`φ² − φ − 1 = 0`** for `φ = 1 + η = 1 + ζ + ζ⁴ = (1 + √5)/2`: the golden ratio realized
inside `ℚ(ζ₅)`, satisfying its defining equation. This is the cyclotomic-side incarnation of the
fundamental unit `φ` whose arithmetic drives `BealGoldenKummerEngine.golden_dual_kummer`. -/
theorem golden_ratio_eq {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (1 + ζ + ζ ^ 4) ^ 2 - (1 + ζ + ζ ^ 4) - 1 = 0 := by
  have hp := golden_subfield_poly hζ
  linear_combination hp

/-! ## Vieta structure: the two real periods are the roots of `x² + x − 1`

The Gaussian periods `η = ζ + ζ⁴` and `η' = ζ² + ζ³` are the two roots of `x² + x − 1`. Their
elementary symmetric functions `η + η' = −1`, `η·η' = −1` (Vieta) pin the minimal polynomial to
`x² + x − 1` (discriminant `5`), giving `η, η' = (−1 ± √5)/2` and hence `ℚ(η) = ℚ(√5) = ℚ(ζ₅)⁺`. -/

/-- The two real periods sum to `−1`: `(ζ + ζ⁴) + (ζ² + ζ³) = −1`. -/
theorem real_periods_sum {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (ζ + ζ ^ 4) + (ζ ^ 2 + ζ ^ 3) = -1 := by
  have hsum := geom_sum_five hζ
  linear_combination hsum

/-- The two real periods multiply to `−1`: `(ζ + ζ⁴)(ζ² + ζ³) = −1`. With the sum, this is Vieta for
`x² + x − 1`. -/
theorem real_periods_prod {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (ζ + ζ ^ 4) * (ζ ^ 2 + ζ ^ 3) = -1 := by
  have h5 : ζ ^ 5 = 1 := hζ.pow_eq_one
  have hsum := geom_sum_five hζ
  linear_combination (ζ + ζ ^ 2) * h5 + hsum

/-- The conjugate period `η' = ζ² + ζ³` also satisfies `x² + x − 1` — both periods are roots. -/
theorem golden_subfield_poly_conj {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (ζ ^ 2 + ζ ^ 3) ^ 2 + (ζ ^ 2 + ζ ^ 3) - 1 = 0 := by
  have h5 : ζ ^ 5 = 1 := hζ.pow_eq_one
  have hsum := geom_sum_five hζ
  linear_combination (ζ + 2) * h5 + hsum

/-- **The golden ratio `φ = 1 + η` is a unit of `𝓞(ℚ(ζ₅))` with inverse `η = ζ + ζ⁴`** (an algebraic
integer): `(1 + ζ + ζ⁴)·(ζ + ζ⁴) = 1`. Both `φ` and `φ⁻¹ = η = φ − 1` are integral, so `φ ∈ 𝓞ˣ` — the
fundamental unit of the real subfield. This is the algebraic core of the open target
`beal_fundamental_unit_sqrt5`: it remains to show `φ` *generates* `(𝓞 ℚ(√5))ˣ` modulo torsion. -/
theorem golden_ratio_mul_inv {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (1 + ζ + ζ ^ 4) * (ζ + ζ ^ 4) = 1 := by
  have hp := golden_subfield_poly hζ
  linear_combination hp

/-- **The field norm of `φ` is `−1`:** `N(φ) = φ·φ̄ = (1+η)(1+η') = -1`, where `φ̄ = 1 + η' = 1 + ζ² + ζ³`
is the Galois conjugate. A unit of norm `−1` is the fundamental-unit signature of the real quadratic
field `ℚ(√5)` (norm form `x² − x − 1`), evidence that `φ` generates `(𝓞 ℚ(√5))ˣ` modulo `±1`. -/
theorem golden_ratio_norm {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (1 + ζ + ζ ^ 4) * (1 + ζ ^ 2 + ζ ^ 3) = -1 := by
  linear_combination real_periods_sum hζ + real_periods_prod hζ

/-! ## Fibonacci bridge: `φⁿ = fib(n-1) + fib(n)·φ` — the link to `BealGoldenKummerEngine`

The arithmetic engine of Kummer `p = 5` (`BealGoldenKummerEngine.five_dvd_fib_iff`) works in the
Fibonacci model `φⁿ = fib(n-1) + fib n · φ`. Here that model is established for the *actual*
cyclotomic golden ratio `φ = 1 + ζ + ζ⁴ ∈ 𝓞(ℚ(ζ₅))`, closing the gap between the abstract engine
and the real subfield element. -/

/-- **Fibonacci power law for any golden element.** If `x² = x + 1` in a commutative ring, then
`x^(n+1) = fib n + fib (n+1) · x`. (The Lucas/Fibonacci identity; `x = φ` is the golden ratio.) -/
theorem pow_succ_fib_of_sq {x : K} (hx : x ^ 2 = x + 1) (n : ℕ) :
    x ^ (n + 1) = (Nat.fib n : K) + (Nat.fib (n + 1) : K) * x := by
  induction n with
  | zero => simp [Nat.fib_one]
  | succ m ih =>
    have hfib : Nat.fib (m + 2) = Nat.fib m + Nat.fib (m + 1) := Nat.fib_add_two
    rw [pow_succ, ih]
    push_cast [hfib]
    linear_combination (Nat.fib (m + 1) : K) * hx

/-- **The cyclotomic golden ratio obeys the Fibonacci power law:**
`φ^(n+1) = fib n + fib (n+1) · φ` for `φ = 1 + ζ + ζ⁴`. This is exactly the model underlying
`BealGoldenKummerEngine.five_dvd_fib_iff` (`φⁿ` rational mod 5 ⟺ `5 ∣ fib n` ⟺ `5 ∣ n`), now tied to
the genuine real-subfield element of `ℚ(ζ₅)`. -/
theorem golden_pow_succ_fib {ζ : K} (hζ : IsPrimitiveRoot ζ 5) (n : ℕ) :
    (1 + ζ + ζ ^ 4) ^ (n + 1) = (Nat.fib n : K) + (Nat.fib (n + 1) : K) * (1 + ζ + ζ ^ 4) := by
  have hx : (1 + ζ + ζ ^ 4) ^ 2 = (1 + ζ + ζ ^ 4) + 1 := by
    have hp := golden_ratio_eq hζ; linear_combination hp
  exact pow_succ_fib_of_sq hx n

end BealFiveRealSubfieldIso
