import Mathlib.NumberTheory.NumberField.CMField
import Mathlib.NumberTheory.NumberField.Ideal.Basic
import Mathlib.Tactic
import Propositio.NumberTheory.Beal.PrimeDescentFiveFull

/-!
# The Hasse unit index `Q = 1` for `ℚ(ζ₅)` — the structural input for Kummer's lemma `p = 5`

The `p = 5` Beal descent (`BealPrimeDescentFiveFull`, `BealFiveUnitInterface`) reduces a
primitive `(5,5,z)` solution to a single open input: pinning the **descent unit**
`u : (𝓞 K)ˣ` (with `K = ℚ(ζ₅)`) — the "infinite-unit gap" `H(u)`. Unlike `p = 3` (finite
unit group, Kummer's lemma in mathlib), `ℤ[ζ₅]` has unit rank `1` and mathlib carries **no
`Five` Kummer lemma**.

The classical proof of Kummer's lemma at `p = 5` first **reduces the rank-`1` unit `u` to a
*real* unit** of the totally real subfield `K⁺ = ℚ(√5)`, via the CM structure
`u = ζ · v` with `v` real. That reduction rests on the **Hasse unit index**
`Q = [(𝓞 K)ˣ : μ_K · (𝓞 K⁺)ˣ] = 1` for prime cyclotomic fields. mathlib has the abstract CM
machinery (`NumberField.IsCMField.indexRealUnits ∈ {1, 2}`) but does **not** compute the index
for any field.

This file proves, unconditionally and axiom-clean, that the index is `1` for `K = ℚ(ζ₅)`:

  `NumberField.IsCMField.indexRealUnits K = 1`.

**Proof.** `indexRealUnits = 2` iff some unit `u` has `t := u·conj(u)⁻¹` generating the full
group `μ_K` of roots of unity (`indexRealUnits_eq_two_iff`). But complex conjugation is the
**identity modulo `λ = ζ − 1`** (both `mk ∘ conj` and `mk` are `ℤ`-algebra maps out of
`𝓞 K = ℤ[ζ]` agreeing on the generator `ζ`, since `ζ ≡ 1 (mod λ)`), so `t ≡ 1 (mod λ)`, hence
every power of `t` is `≡ 1 (mod λ)`. Were `⟨t⟩ = μ_K`, then `−1 ∈ ⟨t⟩`, giving `−1 ≡ 1`, i.e.
`λ ∣ 2` — false, as `N(λ) = 5` is odd (`lambda_dvd_intCast_iff_five`). So the index is `1`.

This is the first quantitative unit-index computation in the corpus and the precise structural
foundation for a future `Five` Kummer lemma: with `Q = 1`, every descent unit is
`(root of unity) · (real unit)`, reducing `H(u)` to the real fundamental unit of `ℚ(√5)`
(`unit_eq_torsion_mul_real`, below).

`lake env lean BealHasseIndex.lean` to typecheck (SLOW — cyclotomic + CM imports).
-/

open NumberField NumberField.Units NumberField.IsCMField Ideal

namespace BealHasseIndex

variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {5} ℚ K]

/-- `ℚ(ζ₅)` is a CM field (totally complex quadratic over its real subfield `ℚ(√5)`). -/
theorem isCMField_five : IsCMField K :=
  IsCyclotomicExtension.Rat.isCMField K (S := {5}) ⟨5, by simp, by norm_num⟩

/-!
## Part 1 — complex conjugation is the identity modulo `λ = ζ − 1`

`mk ∘ conj` and `mk` are both ring maps `𝓞 K → 𝓞 K ⧸ (λ)` agreeing on the ring generator
`ζ` (since `ζ ≡ 1 (mod λ)` and `conj ζ` is a conjugate root, also `≡ 1`). As `𝓞 K = ℤ[ζ]`,
they agree everywhere: `conj x ≡ x (mod λ)` for all `x`.
-/

/-- **Conjugation is trivial mod `λ`.** For all `x : 𝓞 K`,
`conj x ≡ x  (mod λ = ζ − 1)`. -/
theorem conj_mk_eq (hζ : IsPrimitiveRoot (ζ : K) 5) (x : 𝓞 K) :
    haveI := isCMField_five (K := K)
    Ideal.Quotient.mk (Ideal.span {hζ.toInteger - 1}) (ringOfIntegersComplexConj K x)
      = Ideal.Quotient.mk (Ideal.span {hζ.toInteger - 1}) x := by
  haveI := isCMField_five (K := K)
  -- `x` lies in the `ℤ`-subalgebra generated by `ζ`, which is all of `𝓞 K`.
  have hx : x ∈ (⊤ : Subalgebra ℤ (𝓞 K)) := Algebra.mem_top
  rw [← IsCyclotomicExtension.Rat.adjoin_singleton_eq_top hζ] at hx
  induction hx using Algebra.adjoin_induction with
  | mem y hy =>
      rw [Set.mem_singleton_iff] at hy; subst hy
      -- both sides are `≡ 1`: `ζ ≡ 1` and the conjugate `conj ζ ≡ 1` (it is `~ λ + 1`).
      have hmem : hζ.toInteger - 1 ∈ Ideal.span {hζ.toInteger - 1} :=
        Ideal.mem_span_singleton_self _
      have e1 : Ideal.Quotient.mk (Ideal.span {hζ.toInteger - 1}) hζ.toInteger = 1 :=
        (Ideal.Quotient.mk_eq_one_iff_sub_mem _).mpr hmem
      have hassoc : Associated (hζ.toInteger - 1)
          (ringOfIntegersComplexConj K hζ.toInteger - 1) := by
        have h := hζ.toInteger_isPrimitiveRoot.associated_sub_one_map_sub_one
          (ringOfIntegersComplexConj K)
        simpa [map_sub, map_one] using h
      have e2 : Ideal.Quotient.mk (Ideal.span {hζ.toInteger - 1})
          (ringOfIntegersComplexConj K hζ.toInteger) = 1 := by
        refine (Ideal.Quotient.mk_eq_one_iff_sub_mem _).mpr ?_
        rw [Ideal.mem_span_singleton]
        exact hassoc.dvd
      rw [e1, e2]
  | algebraMap r =>
      have hfix : ringOfIntegersComplexConj K (algebraMap ℤ (𝓞 K) r)
          = algebraMap ℤ (𝓞 K) r := by
        rw [eq_intCast (algebraMap ℤ (𝓞 K)) r, map_intCast]
      rw [hfix]
  | add a b _ _ iha ihb =>
      rw [map_add (ringOfIntegersComplexConj K) a b,
          map_add (Ideal.Quotient.mk _) _ _, iha, ihb,
          map_add (Ideal.Quotient.mk _) a b]
  | mul a b _ _ iha ihb =>
      rw [map_mul (ringOfIntegersComplexConj K) a b,
          map_mul (Ideal.Quotient.mk _) _ _, iha, ihb,
          map_mul (Ideal.Quotient.mk _) a b]

/-!
## Part 2 — the unit index is `1`

`indexRealUnits = 2` would give a unit `u` with `t = u·conj(u)⁻¹` generating `μ_K`. But by
Part 1, `t ≡ 1 (mod λ)`, so `⟨t⟩ ⊆ {ε ≡ 1 (mod λ)}` which excludes `−1` (as `λ ∤ 2`). So no
such `u`, and the index is `1`.
-/

/-- **HEADLINE — the Hasse unit index is `1` for `ℚ(ζ₅)`.**
`[(𝓞 K)ˣ : μ_K · (𝓞 K⁺)ˣ] = 1`, i.e. the roots of unity together with the real units
exhaust `(𝓞 K)ˣ`. mathlib computes this index for no field; this is the `p = 5` case. -/
theorem indexRealUnits_eq_one (hζ : IsPrimitiveRoot (ζ : K) 5) :
    haveI := isCMField_five (K := K)
    NumberField.IsCMField.indexRealUnits K = 1 := by
  haveI := isCMField_five (K := K)
  rcases indexRealUnits_eq_one_or_two K with h | h
  · exact h
  · exfalso
    rw [indexRealUnits_eq_two_iff] at h
    obtain ⟨u, hu⟩ := h
    set I := Ideal.span {hζ.toInteger - 1} with hI
    -- the reduction-to-quotient unit homomorphism `φ : (𝓞 K)ˣ → (𝓞 K ⧸ λ)ˣ`
    set φ : (𝓞 K)ˣ →* (𝓞 K ⧸ I)ˣ := Units.map (Ideal.Quotient.mk I).toMonoidHom with hφ
    -- coercion: `↑(φ a) = mk ↑a`
    have hφcoe : ∀ a : (𝓞 K)ˣ, (φ a : 𝓞 K ⧸ I) = Ideal.Quotient.mk I (a : 𝓞 K) := by
      intro a; rw [hφ]; rfl
    -- `φ` agrees on `u` and `conj u`, because `conj ≡ id (mod λ)` (Part 1).
    have hconj : φ (unitsComplexConj K u) = φ u := by
      apply Units.ext
      rw [hφcoe, hφcoe]
      have hbridge : ((unitsComplexConj K u : (𝓞 K)ˣ) : 𝓞 K)
          = ringOfIntegersComplexConj K (u : 𝓞 K) := rfl
      rw [hbridge, hI, conj_mk_eq hζ (u : 𝓞 K)]
    -- (a) `φ (↑t) = 1`, where `t = u·conj(u)⁻¹`.
    have hφt : φ (↑(unitsMulComplexConjInv K u)) = 1 := by
      rw [unitsMulComplexConjInv_apply, map_mul, map_inv, hconj]
      group
    -- (b) `-1 ∈ ⟨t⟩` since `⟨t⟩ = ⊤`.
    have hneg : (⟨-1, neg_one_mem_torsion⟩ : torsion K) ∈
        Subgroup.zpowers (unitsMulComplexConjInv K u) := by
      rw [hu]; exact Subgroup.mem_top _
    obtain ⟨k, hk⟩ := hneg
    -- push to `(𝓞 K)ˣ`: `(↑t)^k = -1`.
    have hk' : (↑(unitsMulComplexConjInv K u) : (𝓞 K)ˣ) ^ k = -1 := by
      have hc := congrArg (fun y : torsion K => (y : (𝓞 K)ˣ)) hk
      simpa [Subgroup.coe_zpow] using hc
    -- apply `φ`: `φ (-1) = 1`, forcing `mk (-1) = 1`, i.e. `λ ∣ 2`.
    have hcontra : φ (-1 : (𝓞 K)ˣ) = 1 := by
      have hc := congrArg φ hk'
      rwa [map_zpow, hφt, one_zpow, eq_comm] at hc
    -- `mk (-1) = 1` in `𝓞 K ⧸ (λ)`
    have hmk : Ideal.Quotient.mk I (-1 : 𝓞 K) = 1 := by
      have hc := congrArg Units.val hcontra
      rw [hφcoe] at hc
      simpa using hc
    -- hence `-1 - 1 = -2 ∈ (λ)`, i.e. `λ ∣ 2` — contradiction (`N λ = 5`).
    have hsub : (-1 : 𝓞 K) - 1 ∈ I := (Ideal.Quotient.mk_eq_one_iff_sub_mem _).mp hmk
    rw [hI, Ideal.mem_span_singleton] at hsub
    have hdvd2 : (hζ.toInteger - 1) ∣ ((2 : ℤ) : 𝓞 K) := by
      have h2 : ((2 : ℤ) : 𝓞 K) = -((-1 : 𝓞 K) - 1) := by push_cast; ring
      rw [h2]; exact dvd_neg.mpr hsub
    rw [BealPrimeDescentFiveFull.lambda_dvd_intCast_iff_five hζ 2] at hdvd2
    norm_num at hdvd2

/-!
## Part 3 — corollary: every unit is `(root of unity) · (real unit)`

The direct payoff for Kummer's lemma: with index `1`, the roots of unity and the real units
generate `(𝓞 K)ˣ`, so any unit factors as `ζ · v` with `ζ` torsion and `v` real. This reduces
the `p = 5` descent-unit gap from "an arbitrary rank-`1` unit" to "the real fundamental unit of
`ℚ(√5)`".
-/

/-- **Every unit of `𝓞(ℚ(ζ₅))` is a root of unity times a real unit.** Consequence of the
index-`1` computation: `(𝓞 K)ˣ = μ_K · (𝓞 K⁺)ˣ`. -/
theorem unit_eq_torsion_mul_real (hζ : IsPrimitiveRoot (ζ : K) 5) (u : (𝓞 K)ˣ) :
    haveI := isCMField_five (K := K)
    ∃ (t : torsion K) (v : (𝓞 K)ˣ), v ∈ realUnits K ∧ u = (t : (𝓞 K)ˣ) * v := by
  haveI := isCMField_five (K := K)
  have htop : realUnits K ⊔ torsion K = ⊤ := by
    have := indexRealUnits_eq_one hζ
    rwa [NumberField.IsCMField.indexRealUnits, Subgroup.index_eq_one] at this
  have hu : u ∈ realUnits K ⊔ torsion K := htop ▸ Subgroup.mem_top u
  rw [Subgroup.mem_sup] at hu
  obtain ⟨v, hv, t, ht, hvt⟩ := hu
  exact ⟨⟨t, ht⟩, v, hv, by rw [← hvt]; exact (mul_comm v t)⟩

end BealHasseIndex
