import Mathlib.RingTheory.RootsOfUnity.Basic
import Mathlib.Tactic

/-!
# The real subfield of `ℚ(ζ₇)` — the cubic generator

The `(7,7,z)` cyclotomic descent (`BealSevenRealReduction`, `BealPrimeRealReduction`) reduces to the
maximal totally real subfield `ℚ(ζ₇)⁺`, a **cubic** field (`[ℚ(ζ₇)⁺ : ℚ] = 3`) generated by the
period `η = ζ + ζ⁻¹ = ζ + ζ⁶ = 2cos(2π/7)`. This file proves the algebraic core, self-contained from
`ζ⁷ = 1` and the geometric sum (no CM machinery), the `p = 7` analogue of `BealFiveRealSubfieldIso`:

* `geom_sum_seven` — `1 + ζ + ⋯ + ζ⁶ = 0`.
* `seven_real_cubic` — `η³ + η² − 2η − 1 = 0`: `η = ζ + ζ⁶` is a root of `X³ + X² − 2X − 1`, the
  minimal polynomial of `2cos(2π/7)` (the totally real cubic of discriminant `49`). This is the
  `p = 7` mirror of `golden_subfield_poly`, the field-theoretic core of the `(7,7,z)` real reduction.
-/

namespace BealSevenRealSubfield

variable {K : Type*} [Field K]

/-- The geometric sum vanishes at a primitive `7`-th root: `1 + ζ + ζ² + ⋯ + ζ⁶ = 0`. -/
theorem geom_sum_seven {ζ : K} (hζ : IsPrimitiveRoot ζ 7) :
    1 + ζ + ζ ^ 2 + ζ ^ 3 + ζ ^ 4 + ζ ^ 5 + ζ ^ 6 = 0 := by
  have h := hζ.geom_sum_eq_zero (by norm_num)
  rw [Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_succ,
    Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_succ,
    Finset.sum_range_one] at h
  simpa [pow_succ] using h

/-- **`η³ + η² − 2η − 1 = 0`** for the real period `η = ζ + ζ⁶ = ζ + ζ⁻¹ = 2cos(2π/7)`: the cubic
generator of `ℚ(ζ₇)⁺` is a root of `X³ + X² − 2X − 1`. The `p = 7` analogue of `golden_subfield_poly`;
together with irreducibility this gives `[ℚ(ζ₇)⁺ : ℚ] = 3`. -/
theorem seven_real_cubic {ζ : K} (hζ : IsPrimitiveRoot ζ 7) :
    (ζ + ζ ^ 6) ^ 3 + (ζ + ζ ^ 6) ^ 2 - 2 * (ζ + ζ ^ 6) - 1 = 0 := by
  have h7 : ζ ^ 7 = 1 := hζ.pow_eq_one
  have hs := geom_sum_seven hζ
  linear_combination (ζ ^ 11 + 3 * ζ ^ 6 + ζ ^ 5 + ζ ^ 4 + 3 * ζ + 2) * h7 + hs

/-- The three Gaussian periods sum to `−1` (the trace): `(ζ+ζ⁶)+(ζ²+ζ⁵)+(ζ³+ζ⁴) = -1`. -/
theorem seven_periods_sum {ζ : K} (hζ : IsPrimitiveRoot ζ 7) :
    (ζ + ζ ^ 6) + (ζ ^ 2 + ζ ^ 5) + (ζ ^ 3 + ζ ^ 4) = -1 := by
  linear_combination geom_sum_seven hζ

/-- The second period `η' = ζ² + ζ⁵` is also a root of `X³ + X² − 2X − 1` — obtained by applying
`seven_real_cubic` to the primitive root `ζ²` (since `(ζ²)⁶ = ζ⁵`). -/
theorem seven_real_cubic_period2 {ζ : K} (hζ : IsPrimitiveRoot ζ 7) :
    (ζ ^ 2 + ζ ^ 5) ^ 3 + (ζ ^ 2 + ζ ^ 5) ^ 2 - 2 * (ζ ^ 2 + ζ ^ 5) - 1 = 0 := by
  have h7 : ζ ^ 7 = 1 := hζ.pow_eq_one
  have h := seven_real_cubic (hζ.pow_of_coprime 2 (by decide))
  have e : (ζ ^ 2) ^ 6 = ζ ^ 5 := by
    have h12 : (ζ ^ 2) ^ 6 = ζ ^ 7 * ζ ^ 5 := by ring
    rw [h12, h7, one_mul]
  rw [e] at h; exact h

/-- The third period `η'' = ζ³ + ζ⁴` is also a root of `X³ + X² − 2X − 1` (via `ζ³`, `(ζ³)⁶ = ζ⁴`).
With the other two, the cubic SPLITS completely in `ℚ(ζ₇)⁺`: it is the totally real (Galois) cubic. -/
theorem seven_real_cubic_period3 {ζ : K} (hζ : IsPrimitiveRoot ζ 7) :
    (ζ ^ 3 + ζ ^ 4) ^ 3 + (ζ ^ 3 + ζ ^ 4) ^ 2 - 2 * (ζ ^ 3 + ζ ^ 4) - 1 = 0 := by
  have h7 : ζ ^ 7 = 1 := hζ.pow_eq_one
  have h := seven_real_cubic (hζ.pow_of_coprime 3 (by decide))
  have e : (ζ ^ 3) ^ 6 = ζ ^ 4 := by
    have h18 : (ζ ^ 3) ^ 6 = (ζ ^ 7) ^ 2 * ζ ^ 4 := by ring
    rw [h18, h7, one_pow, one_mul]
  rw [e] at h; exact h

end BealSevenRealSubfield
