import Propositio.Beal.CyclotomicUnitIndex
import Mathlib.Tactic

/-!
# Unit-group structure of `ℚ(ζ_p)` — generated by roots of unity and real fundamental units

The clean structural consequence of the Hasse index `Q = 1` (`BealCyclotomicUnitIndex`): for every
odd prime `p`, the unit group `(𝓞 ℚ(ζ_p))ˣ` is generated by the roots of unity `μ_K` together with
the **real fundamental system** `realFundSystem K` (the fundamental units of the maximal real
subfield `ℚ(ζ_p)⁺`). Equivalently `μ_K · (𝓞 K⁺)ˣ = (𝓞 K)ˣ`.

This is the explicit "every unit is `(root of unity) · (real unit)`" structure in subgroup form,
and needs **no rank computation** — it follows from mathlib's
`closure_realFundSystem_sup_torsion` (which reduces real units to the real fundamental system) and
`indexRealUnits_eq_one` (which says `μ_K · realUnits = ⊤`).

`lake env lean BealCyclotomicUnitStructure.lean` to typecheck (SLOW — cyclotomic + CM imports).
-/

open NumberField NumberField.Units NumberField.IsCMField

namespace BealCyclotomicUnitStructure

variable {p : ℕ} [hpp : Fact p.Prime] {K : Type*} [Field K] [NumberField K]
  [IsCyclotomicExtension {p} ℚ K] [IsCMField K]

/-- **Unit group of `ℚ(ζ_p)` = `⟨μ_K, real fundamental units⟩`** (every odd prime `p`).
The roots of unity together with the real fundamental system generate the whole unit group —
the subgroup form of `unit_eq_torsion_mul_real`, and the explicit Dirichlet-plus-`Q=1` structure
of `(𝓞 K)ˣ` (no rank computation needed). -/
theorem unitGroup_eq_torsion_join_realFundSystem {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hodd : p ≠ 2) :
    Subgroup.closure (Set.range (realFundSystem K)) ⊔ torsion K = ⊤ := by
  rw [closure_realFundSystem_sup_torsion]
  have h := BealCyclotomicUnitIndex.indexRealUnits_eq_one hζ hodd
  rwa [NumberField.IsCMField.indexRealUnits, Subgroup.index_eq_one] at h

end BealCyclotomicUnitStructure
