import Propositio.Beal.FiveRealSubfieldIso
import Mathlib.RingTheory.RootsOfUnity.Basic
import Mathlib.Tactic

/-!
# Frobenius mod λ⁴ for p = 5: key descent module tool

This file establishes the central mod-λ⁴ Frobenius theorem needed for the Kummer
descent in the `(5,5,z)` Beal case:

**Theorem**: in any field K containing a primitive 5th root of unity `ζ`, if
`λ = 1 − ζ`, then `(1−ζ) ∣ (α−β)` implies `(1−ζ)⁴ ∣ (α⁵ − β⁵)`.

## Algebraic key: (1−ζ)⁴ ∣ 5

The proof hinges on a single ring identity: `(1−ζ)⁴ · (−1−ζ+ζ³) = 5`.

**Derivation** (from ζ⁵ = 1 and the cyclotomic relation Φ₅(ζ) = 0):
  `(1−ζ)⁴ · (−1−ζ+ζ³) = 4 − (ζ+ζ²+ζ³+ζ⁴) = 4 − (−1) = 5`.

Equivalently: `(1−ζ)⁴ = 5·(−ζ+ζ²−ζ³)` (the standard ring identity), and
`(−ζ+ζ²−ζ³)·(−1−ζ+ζ³) = 1` (explicit inverse, proved by `linear_combination (1−ζ)·h5`).

## Frobenius proof

Write α = β + λc (λ = 1−ζ). The binomial expansion:
  α⁵ − β⁵ = 5β⁴λc + 10β³λ²c² + 10β²λ³c³ + 5βλ⁴c⁴ + λ⁵c⁵.

Setting u := −1−ζ+ζ³ (the witness for 5 = λ⁴·u), the witness for λ⁴ ∣ (α⁵−β⁵) is:
  W := u·β⁴·λ·c + 2u·β³·λ²·c² + 2u·β²·λ³·c³ + 5·β·c⁴ + λ·c⁵.

The identity `(1−ζ)⁴ · W = α⁵ − β⁵` then closes by `linear_combination coeff * hu`
where `hu : 5 = (1−ζ)⁴ · u` and coeff = β⁴·λc + 2β³·λ²c² + 2β²·λ³c³.

## Connection to Kummer p = 5

This Frobenius theorem is the key tool for analyzing the mod-λ⁴ residue of the descent
element d^z in `A + B·ζ = d^z · u`. If `λ ∤ d` (case 2), the Frobenius tells us
d^5 ≡ (d mod λ) (mod λ⁴), pinning the mod-λ⁴ residue of d^z in terms of (d mod λ).
This feeds into the torsion-exponent formula for u, enabling the Kummer step.

Axiom status: **all theorems axiom-clean** (`[propext, Classical.choice, Quot.sound]`).

Typecheck: `lake env lean BealKummerDescentMod5.lean`
-/

namespace BealKummerDescentMod5

variable {K : Type*} [Field K]

open BealFiveRealSubfieldIso (geom_sum_five)

/-! ## §1  Core ring identities -/

/-- **`(1−ζ)⁴ = 5·(−ζ+ζ²−ζ³)`**: the standard ramification identity showing
that 5 factors through λ⁴ in ℤ[ζ₅].

Proof: LHS − RHS = 1+ζ+ζ²+ζ³+ζ⁴ = 0 (the cyclotomic relation Φ₅(ζ) = 0). -/
theorem lambda_pow4_eq_five_mul {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (1 - ζ)^4 = 5 * (-ζ + ζ^2 - ζ^3) := by
  have hsum := geom_sum_five hζ
  linear_combination hsum

/-- **`(−ζ+ζ²−ζ³) · (−1−ζ+ζ³) = 1`**: the element `−ζ+ζ²−ζ³` is a unit
in ℤ[ζ₅], with explicit inverse `−1−ζ+ζ³`.

Proof: product = ζ + ζ⁵ − ζ⁶ = ζ + 1 − ζ = 1 (using ζ⁵ = 1, ζ⁶ = ζ). -/
theorem neg_zeta_sum_mul_inv {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (-ζ + ζ^2 - ζ^3) * (-1 - ζ + ζ^3) = 1 := by
  have h5 : ζ^5 = 1 := hζ.pow_eq_one
  linear_combination (1 - ζ) * h5

/-- **`(1−ζ)⁴ · (−1−ζ+ζ³) = 5`**: the key divisibility witness.

From `lambda_pow4_eq_five_mul`: `(1−ζ)⁴ = 5c` where `c = −ζ+ζ²−ζ³`.
And `neg_zeta_sum_mul_inv` gives `c · c⁻¹ = 1` with `c⁻¹ = −1−ζ+ζ³`.
Hence `(1−ζ)⁴ · c⁻¹ = 5c · c⁻¹ = 5`.

Direct proof: `(1−ζ)⁴·(−1−ζ+ζ³) = 4 − (ζ+ζ²+ζ³+ζ⁴) = 4+1 = 5` (using Φ₅(ζ)=0). -/
theorem lambda_pow4_mul_inv_eq_five {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (1 - ζ)^4 * (-1 - ζ + ζ^3) = 5 := by
  have h5 : ζ^5 = 1 := hζ.pow_eq_one
  have hsum := geom_sum_five hζ
  -- Residual after -hsum: -5+4ζ-ζ²+5ζ⁵-4ζ⁶+ζ⁷ = (5-4ζ+ζ²)·(ζ⁵-1), closed by h5
  linear_combination (5 - 4 * ζ + ζ^2) * h5 - hsum

/-- **`(1−ζ)⁴ ∣ 5`**: the element 5 lies in the ideal generated by λ⁴ = (1−ζ)⁴.

This is the ring-theoretic form of the total ramification: the prime 5 is divisible
by λ⁴ in 𝓞(ℚ(ζ₅)) = ℤ[ζ₅].  The witness is `−1−ζ+ζ³ ∈ ℤ[ζ₅]`. -/
theorem lambda_pow4_dvd_five {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    (1 - ζ)^4 ∣ (5 : K) :=
  ⟨-1 - ζ + ζ^3, (lambda_pow4_mul_inv_eq_five hζ).symm⟩

/-! ## §2  The Frobenius theorem -/

/-- **Frobenius mod λ⁴**: if `(1−ζ) ∣ (α−β)` in a field containing a primitive
5th root `ζ`, then `(1−ζ)⁴ ∣ (α⁵ − β⁵)`.

This is the key Kummer-descent tool: the 5th-power map boosts a mod-λ congruence
to a mod-λ⁴ congruence, using the total ramification `5 = (1−ζ)⁴ · (−1−ζ+ζ³)`.

**Proof sketch**:
- Write α = β + λc (from the divisibility hypothesis).
- Binomial: α⁵−β⁵ = 5β⁴λc + 10β³λ²c² + 10β²λ³c³ + 5βλ⁴c⁴ + λ⁵c⁵.
- Setting u = −1−ζ+ζ³ (witness for 5 = λ⁴u), the explicit witness is
  W = u·β⁴·λc + 2u·β³·λ²c² + 2u·β²·λ³c³ + 5·βc⁴ + λc⁵,
  and `λ⁴·W = α⁵−β⁵` closes by `linear_combination coeff·hu`. -/
theorem five_pow_congr_mod_lambda4 {ζ : K} (hζ : IsPrimitiveRoot ζ 5)
    (α β : K) (h : (1 - ζ) ∣ (α - β)) :
    (1 - ζ)^4 ∣ (α^5 - β^5) := by
  obtain ⟨c, hc⟩ := h
  -- hu : 5 = (1-ζ)^4 * u, with u = -1-ζ+ζ^3
  obtain ⟨u, hu⟩ := lambda_pow4_dvd_five hζ
  -- hα : α = β + (1-ζ)·c
  have hα : α = β + (1 - ζ) * c := by linear_combination hc
  -- Provide the explicit divisibility witness W
  refine ⟨u * β^4 * (1 - ζ) * c + 2 * u * β^3 * (1 - ζ)^2 * c^2 +
         2 * u * β^2 * (1 - ζ)^3 * c^3 + 5 * β * c^4 + (1 - ζ) * c^5, ?_⟩
  rw [hα]
  -- Close: (β+(1-ζ)c)^5 - β^5 = (1-ζ)^4 · W, using 5 = (1-ζ)^4·u
  -- residual: (5 - (1-ζ)^4·u) · (β^4(1-ζ)c + 2β^3(1-ζ)^2c^2 + 2β^2(1-ζ)^3c^3) = 0
  linear_combination
    (β^4 * (1 - ζ) * c + 2 * β^3 * (1 - ζ)^2 * c^2 + 2 * β^2 * (1 - ζ)^3 * c^3) * hu

/-! ## §3  Corollaries -/

/-- **Frobenius for integers**: if `(1−ζ) ∣ (α − n)` for an integer `n : ℤ` cast to K,
then `(1−ζ)⁴ ∣ (α⁵ − n)`.

This is the form used in the Beal descent: d ≡ d₀ (mod λ) implies d^5 ≡ d₀ (mod λ⁴),
since d₀^5 ≡ d₀ (mod 5) by Fermat's little theorem (and 5 ∈ (λ⁴)). -/
theorem five_pow_congr_int_mod_lambda4 {ζ : K} (hζ : IsPrimitiveRoot ζ 5)
    (α : K) (n : ℤ) (h : (1 - ζ) ∣ (α - n)) :
    (1 - ζ)^4 ∣ (α^5 - n) := by
  -- n^5 ≡ n (mod 5) by Fermat's little theorem (decidable in ZMod 5)
  have hfermat : (5 : ℤ) ∣ (n^5 - n) := by
    have key : ∀ k : ZMod 5, k ^ 5 = k := by decide
    have hzmod : ((n : ZMod 5)) ^ 5 - (n : ZMod 5) = 0 := by rw [key]; ring
    have h5z : ((n^5 - n : ℤ) : ZMod 5) = 0 := by push_cast; exact hzmod
    exact_mod_cast (ZMod.intCast_zmod_eq_zero_iff_dvd (n^5 - n) 5).mp h5z
  have h5_dvd : (5 : ℤ) ∣ (n^5 - n) := hfermat
  obtain ⟨k, hk⟩ := h5_dvd
  -- (1-ζ)^4 ∣ (n^5 - n) in K via lambda_pow4_dvd_five
  have hdvd_ferm : (1 - ζ)^4 ∣ ((n^5 - n : ℤ) : K) := by
    rw [show ((n^5 - n : ℤ) : K) = (5 : K) * (k : K) by push_cast [hk]; ring]
    exact (lambda_pow4_dvd_five hζ).mul_right (k : K)
  -- (1-ζ)^4 ∣ (α^5 - n^5) by the main Frobenius theorem
  have hdvd_alpha : (1 - ζ)^4 ∣ (α^5 - (n : K)^5) :=
    five_pow_congr_mod_lambda4 hζ α (n : K) (by exact_mod_cast h)
  -- Combine: α^5 - n = (α^5 - n^5) + (n^5 - n)
  have : α^5 - (n : K) = (α^5 - (n : K)^5) + ((n^5 - n : ℤ) : K) := by push_cast; ring
  rw [this]
  exact hdvd_alpha.add hdvd_ferm

/-! ## §4  Ramification corollary -/

/-- **Norm of the unit witness**: the element `−1−ζ+ζ³` has the same divisibility
footprint as a unit — it witnesses `(1−ζ)⁴ ∣ 5` — and its product with `−ζ+ζ²−ζ³` is 1,
confirming both elements are units of norm ±1. -/
theorem lambda_inv_mul_lambda_is_unit {ζ : K} (hζ : IsPrimitiveRoot ζ 5) :
    IsUnit ((-ζ + ζ^2 - ζ^3) : K) := by
  -- In a field, IsUnit ↔ ne_zero; ne_zero follows from the product = 1 identity
  rw [isUnit_iff_ne_zero]
  intro h
  have hmul := neg_zeta_sum_mul_inv hζ
  simp [h] at hmul

end BealKummerDescentMod5
